services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
      - ./nginx/auth:/etc/nginx/auth:ro
      - ./wars:/usr/share/nginx/html/wars:ro
    depends_on:
      - tomcat
    restart: unless-stopped

  tomcat:
    image: tomcat:9-jre11
    ports:
      - "8080:8080"
    volumes:
      - ./wars:/usr/local/tomcat/webapps:rw
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1g
    restart: unless-stopped

  inference:
    build: ./inference
    ports:
      - "9000:9000"
    volumes:
      - ./kortex_model:/app/kortex_model
    restart: unless-stopped
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped

  # optional: grafana (comment in if you want a dashboard)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
